### ISSUE TITLE
Add HCX Appliance healthcheck process before initiate Migration! in www.avshub.io portal

### ISSUE THREAD

**Issue by kambamchanu** [Azure/avshub#5]
Hi Team,
It's glad to share feedback here. I reviewed the steps and documents provided in https://www.avshub.io/ . Its clear to understand end to end HCX configuration. I would like to add one missing part in this particular portal. 

It would be really great if we amend HCX appliance basic health check procedure/ ccli commands before initiating migrations (like probe check/perftest /communication etc.,).
 
![image](https://github.com/Azure/avshub/assets/139100067/cddeacdc-bc17-4d9b-8422-5df0355bab2c)

**Comment by husamhilal** [comment]
This is a great suggestion. I added a reference to this troubleshooting step in Module 2 Task 13. However, I will plan into adding more specific steps in the near future. Thank you so much @kambamchanu  for your contribution.  

Please see: https://www.avshub.io/workshop-guide/module-2/module-2-task-13/
